# Generated by Django 6.0 on 2025-12-30 17:38

from django.db import migrations

def create_groups(apps, schema_editor):
    # Get models through the apps registry
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # 1. Create the Admin and User groups
    admin_group, _ = Group.objects.get_or_create(name='Admin_group')
    user_group, _ = Group.objects.get_or_create(name='User_group')

    # 2. Assign permissions from different apps
    codenames = [
        ('can_manage_users', 'users', ('admin')),
        #('add_user', 'users', ('admin')),
        ('add_request', 'inventory', ('user')),
        ('view_request', 'inventory', ('admin', 'user')),
        ('change_request', 'inventory', ('admin', 'user')),
        ('delete_request', 'inventory', ('admin', 'user')),
        ('global_view_requests', 'inventory', ('admin')),
        ('global_change_requests', 'inventory', ('admin')),
        ('global_delete_requests', 'inventory', ('admin')),
        ('add_request_detail', 'inventory', ('user')),
        ('view_request_detail', 'inventory', ('admin', 'user')),
        ('change_request_detail', 'inventory', ('admin', 'user')),
        ('delete_request_detail', 'inventory', ('admin', 'user')),
        ('add_product', 'inventory', ('admin', 'user')), 
        ('view_product', 'inventory', ('admin', 'user')),
        ('change_product', 'inventory', ('admin', 'user')),
        ('delete_product', 'inventory', ('admin', 'user')),
        ('global_view_buildings', 'inventory', ('admin')),
        ('add_building', 'inventory', ('admin')),
        ('view_building', 'inventory', ('admin', 'user')),
        ('change_building', 'inventory', ('admin')),
        ('delete_building', 'inventory', ('admin')),
        ('add_department', 'inventory', ('admin', 'user')),
        ('view_department', 'inventory', ('admin', 'user')),
        ('change_department', 'inventory', ('admin', 'user')),
        ('delete_department', 'inventory', ('admin', 'user')),
    ]
    for codename, app_label, roles in codenames:
        try:
            permission = Permission.objects.get(codename=codename, content_type__app_label=app_label)
            if 'admin' in roles:
                admin_group.permissions.add(permission)
            if 'user' in roles:
                user_group.permissions.add(permission)
        except Permission.DoesNotExist:
            print(f"Permission {codename} not found for {app_label}")

#--------->for a better performance follow this approach:<------------------
#------------------------------------------------------------------------------------------
# def create_groups(apps, schema_editor):
#     Group = apps.get_model('auth', 'Group')
#     Permission = apps.get_model('auth', 'Permission')
#
#     admin_group, _ = Group.objects.get_or_create(name='Admin_group')
#     user_group, _ = Group.objects.get_or_create(name='User_group')
#
#     # 1. Separate your codenames into lists
#     admin_only_codes = ['can_manage_users', 'global_view_requests']
#     shared_codes = ['view_request', 'change_request', 'view_product']
#     user_only_codes = ['add_request']
#
#     # 2. Fetch all permissions in ONE query per list
#     # (Using codename__in to get them all at once)
#     admin_perms = Permission.objects.filter(codename__in=admin_only_codes + shared_codes)
#     user_perms = Permission.objects.filter(codename__in=user_only_codes + shared_codes)
#
#     # 3. Add them in bulk
#     # *admin_perms "unpacks" the list so Django adds them in a single SQL statement
#     admin_group.permissions.add(*admin_perms)
#     user_group.permissions.add(*user_perms)
#------------------------------------------------------------------------------------------
def remove_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Admin_group').delete()
    Group.objects.filter(name='User_group').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('inventory', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_roles),
    ]
