# Generated by Django 6.0 on 2026-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_establishing_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_must_change',
            field=models.BooleanField(default=True),
        ),
    ]
