# Generated by Django 6.0 on 2026-03-30 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_must_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_picture',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile_picture',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile_picture',
            name='picture_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile_picture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
